config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "books#index"
  resources :books, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body_temperature.rb
class BodyTemperature < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '35.5度' },
    { id: 2, name: '35.6度' },
    { id: 3, name: '35.7度' },
    { id: 4, name: '35.8度' },
    { id: 5, name: '35.9度' },
    { id: 6, name: '36.0度' },
    { id: 7, name: '36.1度' },
    { id: 8, name: '36.2度' },
    { id: 9, name: '36.3度' },
    { id: 10, name: '36.4度' },
    { id: 11, name: '36.5度' },
    { id: 12, name: '36.6度' },
    { id: 13, name: '36.7度' },
    { id: 14, name: '36.8度' },
    { id: 15, name: '36.9度' },
    { id: 16, name: '37.0度' },
    { id: 17, name: '37.1度' },
    { id: 18, name: '37.2度' },
    { id: 19, name: '37.3度' },
    { id: 20, name: '37.4度' },
  ]
  include ActiveHash::Associations
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    
      extend ActiveHash::Associations::ActiveRecordExtensions
      belongs_to :presence
      belongs_to :mood
      belongs_to :body_temperature
      belongs_to :sleep
      belongs_to :reason
      belongs_to :period

      validates :presence_id, presence: true, numericality: { other_than: 0 }
end
    

app/models/mood.rb
class Mood < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'ご機嫌です' },
    { id: 2, name: 'いつも通り' },
    { id: 3, name: 'ご機嫌ななめ' },
  ]
  include ActiveHash::Associations
  has_many :books
end

app/models/period.rb
class Period < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '今日だけ' },
    { id: 2, name: '明日まで' },
    { id: 3, name: '明後日まで' },
    { id: 4, name: 'また再度お知らせします' },
  ]
  include ActiveHash::Associations
  has_many :books
end

app/models/presence.rb
class Presence < ActiveHash::Base
  self.data = [
    { id: 0, name: '0.--' },
    { id: 1, name: '1.出席します！！' },
    { id: 2, name: '2.欠席します' },
  ]
  include ActiveHash::Associations
  has_many :books
end

app/models/reason.rb
class Reason < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '都合欠です' },
    { id: 2, name: '病欠です' },
  ]
  include ActiveHash::Associations
  has_many :books
end

app/models/sleep.rb
class Sleep < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'ぐっすり眠れました' },
    { id: 2, name: '少し夜ふかししました' },
    { id: 3, name: '夜中ちょくちょく目が覚めました' },
    { id: 4, name: 'ほとんど寝てないです' },
  ]
  include ActiveHash::Associations
  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :email, presence: true
         VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze 
         validates :password, 
                    presence: true, length: { minimum: 6 }, format: { with: VALID_PASSWORD_REGEX }     
         validates :child_name, presence: true, format: { with: /\A[ぁ-ゔァ-ヴー一-龥々]+\z/ }
         validates :classroom, presence: true, format: { with: /\A[ぁ-ゔァ-ヴー一-龥々]+\z/ }
         validates :childminder1, presence: true, format: { with: /\A[ぁ-ゔァ-ヴー一-龥々]+\z/ }
         
       
         has_many :books  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:child_name, :classroom, :childminder1, :childminder2, :childminder3])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      render :create
    else
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:presence_id, :mood_id, :body_temperature_id, :sleep_id, :breakfast, :comment1, :reason_id, :period_id, :comment2).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/create.html.erb
<div class="main">
 <div class="contents">
    <div class="success">
      <h3>
        連絡帳が送信されました！
      </h3>
      <%=link_to "トップへ戻る", root_path, class: :success_btn%>
    </div>
    <div class="second_pict"><%= image_tag "775447.png", size: "400x600" %></div>
    <div class="success_comment">
     <p>〜今日も1日いい日でありますように〜</p>
   </div>
 </div>
</div>

app/views/books/index.html.erb
<div class='main'>
  <div class='top_greeting'>
      <% if user_signed_in? %>
         <%=link_to "ログアウトする", destroy_user_session_path, method: :delete,class: :greeting_logout%>
      <% else %>
         <%=link_to "ログインする", new_user_session_path, class: :greeting_btn%>
         <%=link_to "新規登録する", new_user_registration_path, class: :greeting_btn%>
      <% end %>
 </div>
  <div class='title-contents'>
     <% if user_signed_in? %>
         <div class='greeting'>
           <div class="under_greeting">
            <div style="margin: 0 auto;
                background-color: #ffc6c6;
                box-shadow: 0 0 0 8px #ffc6c6;
                border: 2px dashed #ffffff;width:900px;"><%= "あつまれ！" %><br />
              <%= "#{current_user.classroom}組さん！！"%></div>
              </div><br />  
           <div class="first_pict">
            <%= image_tag "619093.png", size: "800x600" %></div>
           <div class="into_btn">
             <%=link_to "入室する", new_book_path %>
           </div>
         </div>
            <% else %>
         <div class='greeting'>
           <div class="under_greeting">
            <div style="margin: 0 auto;
                background-color: #ffc6c6;
                box-shadow: 0 0 0 8px #ffc6c6;
                border: 2px dashed #ffffff;width:900px;"><%= "あつまれ！" %><br />
            <%= "スクスク組さん！！"%></div>
            </div><br />
            <div class="first_pict">
            <%= image_tag "619093.png", size: "800x600" %></div>
         </div>
            <% end %>
      </div>
            
         
         
</div>

app/views/books/new.html.erb
<div class='main'>
   <div class="form_wrap">
     <div class="date-greeting">
      <%= I18n.l Date.today, format: :long %>
      </div>
      <div class="today_book">
        <p><%= image_tag "school002.png", size: "50x40" %></p>
        <p><%="#{current_user.child_name}ちゃんの連絡帳" %></p>
        <p><%= image_tag "school002.png", size: "50x40" %></p>
     </div>

<%= form_with model: @book, url: books_path, class: 'books-main', local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>


  <div class="form-text">
   <div class="form-presence">
    1. 本日の出欠をきかせてください
      </div>
       <%= f.collection_select(:presence_id, Presence.all, :id, :name, {}, {class:"select-box", id:"books_presence"}) %>
      <div class="form-text-attendance">
       <div class="form-attendance">
          2. 出席の方は以下を記入してください
          </div>
          <ul class="attendance-list">
            <li class="list">① 今朝の機嫌はどうでしたか？</li>
              <%= f.collection_select(:mood_id, Mood.all, :id, :name, {}, {class:"select-box", id:"books_mood"}) %>
            <li class="list">② 今朝の体温は何度でしたか？<br />
                               (37.5度以上の場合は登園できません)</li>
              <%= f.collection_select(:body_temperature_id, BodyTemperature.all, :id, :name, {}, {class:"select-box", id:"books_body_temperature"}) %>
            <li class="list">③ 昨夜はよく眠れましたか？</li>
              <%= f.collection_select(:sleep_id, Sleep.all, :id, :name, {}, {class:"select-box", id:"books_sleep"}) %>
            <li class="list">④ 朝食は何を食べましたか？</li>
              <%= f.text_area :breakfast, class:"books-text", id:"book-breakfast", maxlength:"40" %>
            <li class="list">⑤ 何か保育士に伝えておきたいことがありますか？</li>
               <%= f.text_area :comment1, class:"books-text", id:"book-comment1", maxlength:"1000" %>
           </ul>
        </div>
      <div class="form-text-absence">
      <div class="form-absence">
      3. 欠席の方は以下を記入してください
      </div>
       <ul class="absence-list">
          <li class="list">① お休みの理由はなんですか？</li>
          <%= f.collection_select(:reason_id, Reason.all, :id, :name, {}, {class:"select-box", id:"books_reason"}) %>
          <li class="list">② お休みの期間はどれくらいになりそうですか？</li>
          <%= f.collection_select(:period_id, Period.all, :id, :name, {}, {class:"select-box", id:"books_period"}) %>
         <li class="list">③ 体調不良が原因の方は症状をお書きください<br>
                          また、病院を受診した場合は、医師のコメントをあわせてお書きください</li>
         <%= f.text_area :comment2, class:"books-text", id:"book-comment1", maxlength:"1000" %>
       </ul>
       </div>
      </div>
        <div class="presence-btn-contents">
           <%= f.submit "送信する", class:"presence-btn" %>
           <%=link_to 'もどる', root_path, class:"back-btn" %>
       </div>
    <% end %> 
  </div>
</div>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sukusukupon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>